- name: Redfox
  url: https://www.redfoxshop.be/
  note: (including a few free stickers)

- name: Zwarte Kat Kollektief
  url: https://www.zwartekat.org/

- sources:
    - name: De Rode Lap België
      url: https://www.derodelap.be/
    - name: De Rode Lap Nederland
      url: https://www.derodelap.nl/

- name: Left Laser
  url: https://leftlaser.com/

- name: Black Mosquito
  url: https://black-mosquito.org/en/

- name: Vrije Bond
  url: https://webshop.vrijebond.org/